// app/admin/layout.tsx
import type { Metadata } from "next";
import AdminPanelData from "../../components/admin-com/AdminPanelData";
import AdminPanelNavigation from "../../components/admin-com/AdminPanelNavigation";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
 
  return (
        <div className="flex overflow-y-hidden">
          {/* Admin panel sidebar */}
          <aside className="min-w-[40%] min-h-screen md:min-w-[30%] sticky top-0 custom-shadow">
            <div className="shadow-black shadow-[4px 0 10px rgba(0,0,0,0.2)]">
              <AdminPanelData />
              <AdminPanelNavigation />
            </div>
          </aside>
          {/* Main content area */}
          <main className=" bg-[var(--background)] flex-1">
          <Link href={'/'} className="h-[10vh] p-4 w-full block bg-[var(--background-secondary)] text-gray-900 text-xl font-medium text-right">Back to home</Link>
            <div className="max-h-[90vh] overflow-y-scroll p-4">
            {children}
            </div>
          </main>
        </div>
  );
}
