import type { Metadata } from "next";
import AdminPanelData from "./AdminPanelData";
import AdminPanelNavigation from "./AdminPanelNavigation";

interface RootLayoutProps {
  children: React.ReactNode;
}

// Define metadata for the admin panel
export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

// Define the RootLayout component
const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {

  return (
    <div>
       {/* Admin panel sidebar */}
       <aside className="min-w-[40%] bg-slate-300 md:min-w-[20%] sticky top-0 custom-shadow">
          <div className="shadow-black shadow-[4px 0 10px rgba(0,0,0,0.2)]">
            <AdminPanelData />
            <AdminPanelNavigation />
          </div>
        </aside>
        {/* Main content area */}
        {children}
    </div>
  );
};

export default RootLayout;